# -*- coding: utf-8 -*-
"""helper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11Poa2a9kXxMh4fTSwQL7cePoDX7ROLTw
"""

def rgbExclusion(image, channel):
  copied_image = image.copy()
  if(channel=='R'):
    copied_image[:,:,0] = 0
  
  if(channel=='G'):
    copied_image[:,:,1] = 0

  if(channel=='B'):
    copied_image[:,:,2] = 0
  return copied_image